/**
 * 애플리케이션에서 사용되는 공통 문자열 상수들
 * 중복 문자열을 상수화하여 유지보수성 향상
 */

// 사용자 관련
export const USER_LABELS = {
  USER: '사용자',
  USERS: '사용자들',
  USER_MANAGEMENT: '사용자 관리',
  USER_PROFILE: '사용자 프로필',
  USER_ADD: '사용자 추가',
  USER_EDIT: '사용자 수정',
  USER_DELETE: '사용자 삭제',
  USER_DETAILS: '사용자 상세 정보',
  USER_ROLE: '사용자 권한',
  USER_STATUS: '사용자 상태',
  USER_GROWTH: '사용자 성장',
  USER_RETENTION: '사용자 유지율',
  ACTIVE_USERS: '활성 사용자',
  TOTAL_USERS: '총 사용자',
} as const;

// 게시글 관련
export const POST_LABELS = {
  POST: '게시글',
  POSTS: '게시글들',
  POST_CREATE: '게시글 작성',
  POST_EDIT: '게시글 수정',
  POST_DELETE: '게시글 삭제',
  POST_DETAILS: '게시글 상세',
  POST_LIST: '게시글 목록',
  POST_MANAGEMENT: '게시글 관리',
  POST_APPROVAL: '게시글 승인',
  POST_CATEGORY: '게시글 카테고리',
  POST_TAGS: '게시글 태그',
  POST_STATUS: '게시글 상태',
  POST_AUTHOR: '게시글 작성자',
  POST_CREATED_AT: '게시글 작성일',
  POST_UPDATED_AT: '게시글 수정일',
  POST_VIEWS: '게시글 조회수',
  POST_LIKES: '게시글 좋아요',
  POST_COMMENTS: '게시글 댓글',
  POST_REPLIES: '게시글 답글',
  POST_POPULAR: '인기 게시글',
  POST_RECENT: '최신 게시글',
  POST_PINNED: '고정 게시글',
  POST_DRAFT: '임시저장 게시글',
  POST_PUBLISHED: '게시된 게시글',
  COMMENT: '댓글',
} as const;

// 프로젝트 관련
export const PROJECT_LABELS = {
  PROJECT: '프로젝트',
  PROJECTS: '프로젝트들',
  PROJECT_CREATE: '프로젝트 생성',
  PROJECT_EDIT: '프로젝트 수정',
  PROJECT_DELETE: '프로젝트 삭제',
  PROJECT_DETAILS: '프로젝트 상세',
  PROJECT_LIST: '프로젝트 목록',
  PROJECT_MANAGEMENT: '프로젝트 관리',
  PROJECT_APPROVAL: '프로젝트 승인',
  PROJECT_CATEGORY: '프로젝트 카테고리',
  PROJECT_STATUS: '프로젝트 상태',
  PROJECT_AUTHOR: '프로젝트 작성자',
  PROJECT_GOAL: '프로젝트 목표',
  PROJECT_CURRENT: '프로젝트 현재',
  PROJECT_FUNDING: '프로젝트 펀딩',
  PROJECT_DEADLINE: '프로젝트 마감일',
  PROJECT_SUBMITTED: '프로젝트 제출일',
  PROJECT_APPROVED: '승인됨',
  PROJECT_REJECTED: '거절됨',
  PROJECT_ACTIVE: '진행중',
  PROJECT_COMPLETED: '완료',
  PROJECT_PENDING: '승인 대기',
  TOTAL_PROJECTS: '총 프로젝트',
} as const;

// 상태 관련
export const STATUS_LABELS = {
  ACTIVE: '활성',
  INACTIVE: '비활성',
  PENDING: '대기',
  APPROVED: '승인됨',
  REJECTED: '거절됨',
  COMPLETED: '완료',
  CANCELLED: '취소됨',
  SUSPENDED: '정지',
  BANNED: '차단',
  DRAFT: '임시저장',
  PUBLISHED: '게시됨',
  REVIEWED: '검토됨',
  RESOLVED: '해결됨',
  HIGH: '높음',
  MEDIUM: '보통',
  LOW: '낮음',
  PENDING_REVIEW: '검토 대기',
  REVIEWED_STATUS: '검토됨',
  RESOLVED_STATUS: '해결됨',
} as const;

// 권한 관련
export const ROLE_LABELS = {
  ADMIN: '관리자',
  ARTIST: '아티스트',
  FAN: '팬',
  USER: '사용자',
  MODERATOR: '모더레이터',
} as const;

// 카테고리 관련
export const CATEGORY_LABELS = {
  MUSIC: '음악',
  ART: '예술',
  TECHNOLOGY: '기술',
  CULTURE: '문화',
  SPORTS: '스포츠',
  OTHER: '기타',
  ALL: '전체',
} as const;

// 액션 관련
export const ACTION_LABELS = {
  CREATE: '생성',
  EDIT: '수정',
  DELETE: '삭제',
  VIEW: '보기',
  APPROVE: '승인',
  REJECT: '거절',
  LIKE: '좋아요',
  UNLIKE: '좋아요 취소',
  COMMENT: '댓글',
  REPLY: '답글',
  SHARE: '공유',
  SAVE: '저장',
  CANCEL: '취소',
  CONFIRM: '확인',
  SUBMIT: '제출',
  UPLOAD: '업로드',
  DOWNLOAD: '다운로드',
  EXPORT: '내보내기',
  IMPORT: '가져오기',
  SEARCH: '검색',
  FILTER: '필터',
  SORT: '정렬',
  REFRESH: '새로고침',
  RETRY: '재시도',
  BACK: '뒤로',
  NEXT: '다음',
  PREVIOUS: '이전',
  CLOSE: '닫기',
  OPEN: '열기',
  SAVE_DRAFT: '임시저장',
  PUBLISH: '게시',
  UNPUBLISH: '게시 취소',
} as const;

// 메시지 관련
export const MESSAGE_LABELS = {
  SUCCESS: '성공',
  ERROR: '오류',
  WARNING: '경고',
  INFO: '정보',
  LOADING: '로딩 중',
  SAVING: '저장 중',
  PROCESSING: '처리 중',
  UPLOADING: '업로드 중',
  DOWNLOADING: '다운로드 중',
  CONNECTING: '연결 중',
  DISCONNECTED: '연결 끊김',
  CONNECTED: '연결됨',
  OFFLINE: '오프라인',
  ONLINE: '온라인',
} as const;

// 폼 관련
export const FORM_LABELS = {
  TITLE: '제목',
  CONTENT: '내용',
  DESCRIPTION: '설명',
  CATEGORY: '카테고리',
  TAGS: '태그',
  STATUS: '상태',
  ROLE: '권한',
  EMAIL: '이메일',
  PASSWORD: '비밀번호',
  USERNAME: '사용자명',
  NAME: '이름',
  PHONE: '전화번호',
  ADDRESS: '주소',
  DATE: '날짜',
  TIME: '시간',
  AMOUNT: '금액',
  PRICE: '가격',
  QUANTITY: '수량',
  DURATION: '기간',
  DEADLINE: '마감일',
  START_DATE: '시작일',
  END_DATE: '종료일',
  REQUIRED: '필수',
  OPTIONAL: '선택',
  MIN_LENGTH: '최소 길이',
  MAX_LENGTH: '최대 길이',
  MIN_VALUE: '최소값',
  MAX_VALUE: '최대값',
} as const;

// 에러 메시지
export const ERROR_MESSAGES = {
  REQUIRED_FIELD: '필수 입력 항목입니다',
  INVALID_EMAIL: '올바른 이메일 형식이 아닙니다',
  INVALID_PASSWORD: '비밀번호 형식이 올바르지 않습니다',
  PASSWORD_MISMATCH: '비밀번호가 일치하지 않습니다',
  LOGIN_REQUIRED: '로그인이 필요합니다',
  PERMISSION_DENIED: '권한이 없습니다',
  NOT_FOUND: '찾을 수 없습니다',
  NETWORK_ERROR: '네트워크 오류가 발생했습니다',
  SERVER_ERROR: '서버 오류가 발생했습니다',
  UNKNOWN_ERROR: '알 수 없는 오류가 발생했습니다',
  VALIDATION_ERROR: '입력값이 올바르지 않습니다',
  UPLOAD_FAILED: '업로드에 실패했습니다',
  DOWNLOAD_FAILED: '다운로드에 실패했습니다',
  SAVE_FAILED: '저장에 실패했습니다',
  DELETE_FAILED: '삭제에 실패했습니다',
  UPDATE_FAILED: '수정에 실패했습니다',
  CREATE_FAILED: '생성에 실패했습니다',
} as const;

// 성공 메시지
export const SUCCESS_MESSAGES = {
  SAVED: '저장되었습니다',
  UPDATED: '수정되었습니다',
  DELETED: '삭제되었습니다',
  CREATED: '생성되었습니다',
  UPLOADED: '업로드되었습니다',
  DOWNLOADED: '다운로드되었습니다',
  PUBLISHED: '게시되었습니다',
  APPROVED: '승인되었습니다',
  REJECTED: '거절되었습니다',
  LIKED: '좋아요를 눌렀습니다',
  UNLIKED: '좋아요를 취소했습니다',
  COMMENTED: '댓글이 작성되었습니다',
  REPLIED: '답글이 작성되었습니다',
  SHARED: '공유되었습니다',
  EXPORTED: '내보내기가 완료되었습니다',
  IMPORTED: '가져오기가 완료되었습니다',
} as const;

// 플레이스홀더
export const PLACEHOLDERS = {
  SEARCH: '검색어를 입력하세요',
  TITLE: '제목을 입력하세요',
  CONTENT: '내용을 입력하세요',
  DESCRIPTION: '설명을 입력하세요',
  TAGS: '태그를 쉼표로 구분하여 입력하세요',
  EMAIL: '이메일을 입력하세요',
  PASSWORD: '비밀번호를 입력하세요',
  USERNAME: '사용자명을 입력하세요',
  NAME: '이름을 입력하세요',
  PHONE: '전화번호를 입력하세요',
  ADDRESS: '주소를 입력하세요',
  COMMENT: '댓글을 입력하세요',
  REPLY: '답글을 입력하세요',
  SEARCH_USERS: '사용자 검색...',
  SEARCH_POSTS: '게시글 검색...',
  SEARCH_PROJECTS: '프로젝트 검색...',
} as const;

// 버튼 텍스트
export const BUTTON_LABELS = {
  SAVE: '저장',
  CANCEL: '취소',
  DELETE: '삭제',
  EDIT: '수정',
  VIEW: '보기',
  CREATE: '생성',
  SUBMIT: '제출',
  APPROVE: '승인',
  REJECT: '거절',
  LIKE: '좋아요',
  COMMENT: '댓글',
  REPLY: '답글',
  SHARE: '공유',
  SAVE_DRAFT: '임시저장',
  PUBLISH: '게시',
  BACK: '뒤로',
  NEXT: '다음',
  PREVIOUS: '이전',
  CLOSE: '닫기',
  OPEN: '열기',
  REFRESH: '새로고침',
  RETRY: '재시도',
  UPLOAD: '업로드',
  DOWNLOAD: '다운로드',
  EXPORT: '내보내기',
  IMPORT: '가져오기',
  SEARCH: '검색',
  FILTER: '필터',
  SORT: '정렬',
  ADD: '추가',
  REMOVE: '제거',
  SELECT: '선택',
  CLEAR: '지우기',
  RESET: '초기화',
  CONFIRM: '확인',
  YES: '예',
  NO: '아니오',
  OK: '확인',
} as const;

// 테이블 헤더
export const TABLE_HEADERS = {
  USER: '사용자',
  ROLE: '권한',
  STATUS: '상태',
  CREATED_AT: '생성일',
  UPDATED_AT: '수정일',
  LAST_LOGIN: '마지막 로그인',
  ACTIONS: '작업',
  TITLE: '제목',
  CONTENT: '내용',
  CATEGORY: '카테고리',
  TAGS: '태그',
  AUTHOR: '작성자',
  VIEWS: '조회수',
  LIKES: '좋아요',
  COMMENTS: '댓글',
  REPLIES: '답글',
  DATE: '날짜',
  TIME: '시간',
  AMOUNT: '금액',
  PRICE: '가격',
  QUANTITY: '수량',
  DURATION: '기간',
  DEADLINE: '마감일',
  START_DATE: '시작일',
  END_DATE: '종료일',
  GOAL: '목표',
  CURRENT: '현재',
  PROGRESS: '진행률',
  COMPLETION: '완료율',
} as const;

// 페이지 제목
export const PAGE_TITLES = {
  HOME: '홈',
  DASHBOARD: '대시보드',
  ADMIN: '관리자',
  USERS: '사용자 관리',
  POSTS: '게시글 관리',
  PROJECTS: '프로젝트 관리',
  COMMUNITY: '커뮤니티',
  EVENTS: '이벤트',
  GALLERY: '갤러리',
  SEARCH: '검색',
  PROFILE: '프로필',
  SETTINGS: '설정',
  NOTIFICATIONS: '알림',
  HELP: '도움말',
  ABOUT: '소개',
  CONTACT: '문의',
  PRIVACY: '개인정보처리방침',
  TERMS: '이용약관',
  LOGIN: '로그인',
  REGISTER: '회원가입',
  FORGOT_PASSWORD: '비밀번호 찾기',
  RESET_PASSWORD: '비밀번호 재설정',
  VERIFY_EMAIL: '이메일 인증',
} as const;

// 빈 상태 메시지
export const EMPTY_STATE_MESSAGES = {
  NO_POSTS: '게시글이 없습니다',
  NO_PROJECTS: '프로젝트가 없습니다',
  NO_USERS: '사용자가 없습니다',
  NO_COMMENTS: '댓글이 없습니다',
  NO_REPLIES: '답글이 없습니다',
  NO_NOTIFICATIONS: '알림이 없습니다',
  NO_RESULTS: '검색 결과가 없습니다',
  NO_DATA: '데이터가 없습니다',
  NO_ITEMS: '항목이 없습니다',
  NO_FILES: '파일이 없습니다',
  NO_IMAGES: '이미지가 없습니다',
  NO_VIDEOS: '비디오가 없습니다',
  NO_AUDIO: '오디오가 없습니다',
  NO_DOCUMENTS: '문서가 없습니다',
  NO_ARCHIVES: '아카이브가 없습니다',
} as const;

// 로딩 메시지
export const LOADING_MESSAGES = {
  LOADING: '로딩 중...',
  SAVING: '저장 중...',
  UPLOADING: '업로드 중...',
  DOWNLOADING: '다운로드 중...',
  PROCESSING: '처리 중...',
  CONNECTING: '연결 중...',
  SEARCHING: '검색 중...',
  FILTERING: '필터링 중...',
  SORTING: '정렬 중...',
  REFRESHING: '새로고침 중...',
  VALIDATING: '검증 중...',
  SUBMITTING: '제출 중...',
  APPROVING: '승인 중...',
  REJECTING: '거절 중...',
  DELETING: '삭제 중...',
  UPDATING: '수정 중...',
  CREATING: '생성 중...',
} as const;
